# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [7]:
# your code here
import pandas as pd
import numpy as np
#from sklearn.preprocessing import normalize

# INPUT
ttt = pd.read_csv('tic-tac-toe.csv')
X = ttt.drop('class', axis = 1)
dt = {'x' : 1, 'o' : 0, 'b' : -1}
X = np.array(X.applymap(dt.get))
#X = normalize(X)
X

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 1, 0, 1],
       [0, 1, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 1]], dtype=int64)

In [8]:
# OUTPUT
y = np.array(ttt['class'].astype('int'))

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [9]:
#X_train.shape, X_test.shape, y_train.shape, y_test.shape

In [15]:
# your code here
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler

# Split.
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)
#X_train = X_train.reshape((-1, 9))
#X_test = X_test.reshape((-1, 9))

# Build the model.
model = Sequential([
  Dense(64, activation = 'relu', input_shape=(9,)),
  Dense(64, activation = 'relu'),
  Dense(2, activation = 'softmax'),
])

# Compile the model.
model.compile(
  optimizer = 'adam',
  loss = 'sparse_categorical_crossentropy',
  metrics = ['accuracy'],
)

# Train the model.
history = model.fit(
  X_train,
  y_train,
  epochs = 5,
  batch_size = 32,
)

# Evaluate the model.
model.evaluate(
  X_test,
  y_test
)

model.save_weights('tic-tac-toe.model.h5')

Epoch 1/5
766/766 [==============================] - 1s 2ms/step - loss: 0.6553 - acc: 0.6110
Epoch 2/5
766/766 [==============================] - 0s 164us/step - loss: 0.5997 - acc: 0.6606
Epoch 3/5
766/766 [==============================] - 0s 151us/step - loss: 0.5717 - acc: 0.6997
Epoch 4/5
766/766 [==============================] - 0s 161us/step - loss: 0.5496 - acc: 0.7232
Epoch 5/5
192/192 [==============================] - 0s 885us/step


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [16]:
# your code here
#model.load_weights('tic-tac-toe.model.h5')
predictions = model.predict(X_test[:20])
print(np.argmax(predictions, axis=1))
print(y_test[:20])

[1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1]
[1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1]


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [18]:
# your code here
model = Sequential([
  Dense(64, activation = 'relu', input_shape=(9,)),
  Dense(64, activation = 'relu'),
  Dense(32, activation = 'relu'),
  Dense(32, activation = 'relu'),
  Dense(2, activation = 'softmax'),
])

model.compile(
  optimizer = 'adam',
  loss = 'sparse_categorical_crossentropy',
  metrics = ['accuracy'],
)

# Train the model.
history = model.fit(
  X_train,
  y_train,
  epochs = 8,
  batch_size = 32,
)

predictions = model.predict(X_test[:20])
print(np.argmax(predictions, axis=1))
print(y_test[:20])

Epoch 1/8
766/766 [==============================] - 2s 2ms/step - loss: 0.6625 - acc: 0.6070
Epoch 2/8
766/766 [==============================] - 0s 202us/step - loss: 0.6027 - acc: 0.6723
Epoch 3/8
766/766 [==============================] - 0s 195us/step - loss: 0.5663 - acc: 0.7063
Epoch 4/8
766/766 [==============================] - 0s 202us/step - loss: 0.5236 - acc: 0.7454
Epoch 5/8
766/766 [==============================] - 0s 193us/step - loss: 0.4772 - acc: 0.7937
Epoch 6/8
766/766 [==============================] - 0s 171us/step - loss: 0.4357 - acc: 0.8068
Epoch 7/8
766/766 [==============================] - 0s 209us/step - loss: 0.4046 - acc: 0.8303
Epoch 8/8
766/766 [==============================] - 0s 198us/step - loss: 0.3536 - acc: 0.8577
[1 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1]
[1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1]


In [31]:
import tensorflow as tf
#from tensorflow.keras.optimizers import Adam
from keras.optimizers import Adam

# your code here
model = Sequential([
  Dense(64, activation = 'relu', input_shape=(9,)),
  Dense(64, activation = 'relu'),
  Dense(64, activation = 'relu'),
  Dense(2, activation = 'softmax'),
])

model.compile(
  optimizer = Adam(lr = 0.01),
  loss = 'sparse_categorical_crossentropy',
  metrics = ['accuracy'],
)

# Train the model.
history = model.fit(
  X_train,
  y_train,
  epochs = 8,
  batch_size = 32,
)

predictions = model.predict(X_test[:20])
print(np.argmax(predictions, axis=1))
print(y_test[:20])

Epoch 1/8
766/766 [==============================] - 3s 4ms/step - loss: 0.6070 - acc: 0.6671
Epoch 2/8
766/766 [==============================] - 0s 206us/step - loss: 0.4498 - acc: 0.7911
Epoch 3/8
766/766 [==============================] - 0s 214us/step - loss: 0.3806 - acc: 0.8355
Epoch 4/8
766/766 [==============================] - 0s 292us/step - loss: 0.2840 - acc: 0.8864
Epoch 5/8
766/766 [==============================] - 0s 335us/step - loss: 0.2264 - acc: 0.9099
Epoch 6/8
766/766 [==============================] - 0s 299us/step - loss: 0.2172 - acc: 0.9112
Epoch 7/8
766/766 [==============================] - 0s 354us/step - loss: 0.1590 - acc: 0.9386
Epoch 8/8
766/766 [==============================] - 0s 338us/step - loss: 0.1131 - acc: 0.9595
[1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1]
[1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1]


**Which approach(es) did you find helpful to improve your model performance?**

### your answer here
- Yes, adding an epoch and small learning rate improved the model.
- However lowering the lr too much did not help.