# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [58]:
import pandas as pd
import numpy as np

In [59]:
# your code here
data=pd.read_csv('tic-tac-toe.csv')
data

TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [60]:
data.replace('x', 1, inplace=True)
data.replace('o', -1, inplace=True)
data.replace('b', 0, inplace=True)
data

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0     1   1   1   1  -1  -1   1  -1  -1   True
1     1   1   1   1  -1  -1  -1   1  -1   True
2     1   1   1   1  -1  -1  -1  -1   1   True
3     1   1   1   1  -1  -1  -1   0   0   True
4     1   1   1   1  -1  -1   0  -1   0   True
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
953  -1   1   1   1  -1  -1  -1   1   1  False
954  -1   1  -1   1   1  -1   1  -1   1  False
955  -1   1  -1   1  -1   1   1  -1   1  False
956  -1   1  -1  -1   1   1   1  -1   1  False
957  -1  -1   1   1   1  -1  -1   1   1  False

[958 rows x 10 columns]

In [61]:
X=np.array(data.drop('class', axis=1))
y=np.array(data['class'])

In [62]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X_scaled=scaler.transform(X)
X_scaled

array([[1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 1., 1.]])

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [63]:
# your code here
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2)

In [64]:
import tensorflow as tf

model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(18, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(18, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(18, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(2, activation=tf.nn.softmax))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


history = model.fit(
  X_train,
  y_train,
  epochs=50,
  batch_size=32)


Train on 766 samples
Epoch 1/50
766/766 [==============================] - 1s 1ms/sample - loss: 0.6933 - accuracy: 0.5509
Epoch 2/50
766/766 [==============================] - 0s 106us/sample - loss: 0.6494 - accuracy: 0.6554
Epoch 3/50
766/766 [==============================] - 0s 87us/sample - loss: 0.6270 - accuracy: 0.6540
Epoch 4/50
766/766 [==============================] - 0s 82us/sample - loss: 0.6060 - accuracy: 0.6593
Epoch 5/50
766/766 [==============================] - 0s 93us/sample - loss: 0.5845 - accuracy: 0.6789
Epoch 6/50
766/766 [==============================] - 0s 84us/sample - loss: 0.5658 - accuracy: 0.6971
Epoch 7/50
766/766 [==============================] - 0s 91us/sample - loss: 0.5502 - accuracy: 0.7115
Epoch 8/50
766/766 [==============================] - 0s 85us/sample - loss: 0.5358 - accuracy: 0.7324
Epoch 9/50
766/766 [==============================] - 0s 91us/sample - loss: 0.5220 - accuracy: 0.7441
Epoch 10/50
766/766 [==============================]

In [65]:
model.evaluate(
  X_test,
  y_test)

192/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.067535649985075, 0.9895833]

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [66]:
# your code here
model.save_weights("tic-tac-toe.model")
model.load_weights("tic-tac-toe.model")

In [70]:
import random
rand_index=[]
for i in range(0,10): 
    rand_index.append(random.randint(1, len(X_test)-1))
    
prediction = model.predict(X_test[rand_index])
predicted = np.argmax(prediction, axis = 1)

In [72]:
predicted, y_test[rand_index]

(array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([False,  True,  True, False,  True,  True,  True,  True,  True,
         True]))

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

My model performed really well. I was able to get a loss below 0.1 and an accuracy higher than 95%. 