# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
import pandas as pd
tic_tac_toe = pd.read_csv('tic-tac-toe.csv')

In [2]:
tic_tac_toe.shape
tic_tac_toe.info()
tic_tac_toe.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool  
dtypes: bool(1), object(9)
memory usage: 68.4+ KB


TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [3]:
coll=list(tic_tac_toe.columns)
display(coll)
coll.remove('class')
coll

['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR', 'class']

['TL', 'TM', 'TR', 'ML', 'MM', 'MR', 'BL', 'BM', 'BR']

In [4]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

for col in coll:
    le.fit(tic_tac_toe[col])
    tic_tac_toe[col]=le.transform(tic_tac_toe[col])

In [5]:
#from sklearn import preprocessing
## applying normalization to my dataset
#norm = preprocessing.MinMaxScaler()
#X_train = norm.fit_transform(X_train)
#X_test = norm.transform(X_test)

#Normalized after splitting

In [6]:
from sklearn import preprocessing


X = tic_tac_toe[['TL', 'TM', 'TR', 'ML','MM' , 'MR', 'BL', 'BM', 'BR']]
y = tic_tac_toe['class']


std = preprocessing.StandardScaler()
X = std.fit_transform(X)

In [7]:
X

array([[ 1.00322257,  1.08495342,  1.00322257, ...,  1.00322257,
        -0.16731812, -0.28682739],
       [ 1.00322257,  1.08495342,  1.00322257, ..., -0.28682739,
         1.08495342, -0.28682739],
       [ 1.00322257,  1.08495342,  1.00322257, ..., -0.28682739,
        -0.16731812,  1.00322257],
       ...,
       [-0.28682739,  1.08495342, -0.28682739, ...,  1.00322257,
        -0.16731812,  1.00322257],
       [-0.28682739,  1.08495342, -0.28682739, ...,  1.00322257,
        -0.16731812,  1.00322257],
       [-0.28682739, -0.16731812,  1.00322257, ..., -0.28682739,
         1.08495342,  1.00322257]])

In [8]:
y

0       True
1       True
2       True
3       True
4       True
       ...  
953    False
954    False
955    False
956    False
957    False
Name: class, Length: 958, dtype: bool

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [10]:
X_train

array([[ 1.00322257, -0.16731812, -0.28682739, ...,  1.00322257,
        -1.41958965,  1.00322257],
       [-1.57687736, -1.41958965, -1.57687736, ...,  1.00322257,
         1.08495342,  1.00322257],
       [-0.28682739,  1.08495342, -1.57687736, ..., -0.28682739,
        -1.41958965, -0.28682739],
       ...,
       [ 1.00322257,  1.08495342, -0.28682739, ..., -0.28682739,
        -0.16731812, -1.57687736],
       [-1.57687736, -0.16731812,  1.00322257, ...,  1.00322257,
         1.08495342,  1.00322257],
       [ 1.00322257, -0.16731812,  1.00322257, ..., -0.28682739,
        -0.16731812, -0.28682739]])

In [11]:
X_test

array([[-1.57687736,  1.08495342,  1.00322257, ..., -0.28682739,
        -0.16731812, -0.28682739],
       [-1.57687736,  1.08495342, -0.28682739, ..., -0.28682739,
        -0.16731812, -1.57687736],
       [ 1.00322257,  1.08495342,  1.00322257, ..., -0.28682739,
        -0.16731812,  1.00322257],
       ...,
       [ 1.00322257, -1.41958965, -1.57687736, ...,  1.00322257,
        -0.16731812, -1.57687736],
       [ 1.00322257, -1.41958965, -1.57687736, ...,  1.00322257,
         1.08495342, -0.28682739],
       [ 1.00322257,  1.08495342,  1.00322257, ..., -0.28682739,
        -0.16731812, -1.57687736]])

In [12]:
y_train

162     True
624     True
346     True
571     True
947    False
       ...  
835    False
192     True
629    False
559     True
684    False
Name: class, Length: 718, dtype: bool

In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [14]:
model = Sequential([ # as far as we know, all networks are sequential
  Dense(64, activation='relu', input_shape=(9,)), # 784= 28*28 dense networks means all neurons in one layer are connected to all neuronsof the next layer
  Dense(64, activation='relu'),      # choosing relu instead of sigmoid, this is somewhat common
  Dense(10, activation='softmax'),   # the softmax actiavation is the last one to compensate for the high volume additions
])

model.compile(
  optimizer='adam', #here we could use stochastic gradient descent, but adam is a de facto standard
  loss='sparse_categorical_crossentropy', #this is how we create the original blam to play the blame game
  metrics=['accuracy'],
)

In [15]:
history = model.fit(
  X_train,
  y_train, # just to make sure the outputs are not considered numeric (because, ya know, they are numbers...)
  epochs=30, # go 5 times through the whole dataset
  batch_size=15, # send 10 images at a time before you tweak the network again, to make it faster
)

Epoch 1/30
48/48 [==============================] - 0s 674us/step - loss: 1.2557 - accuracy: 0.5989
Epoch 2/30
48/48 [==============================] - 0s 537us/step - loss: 0.6503 - accuracy: 0.6838
Epoch 3/30
48/48 [==============================] - 0s 499us/step - loss: 0.5793 - accuracy: 0.7131
Epoch 4/30
48/48 [==============================] - 0s 574us/step - loss: 0.5560 - accuracy: 0.7187
Epoch 5/30
48/48 [==============================] - 0s 520us/step - loss: 0.5211 - accuracy: 0.7604
Epoch 6/30
48/48 [==============================] - 0s 499us/step - loss: 0.4908 - accuracy: 0.7925
Epoch 7/30
48/48 [==============================] - 0s 587us/step - loss: 0.4624 - accuracy: 0.7981
Epoch 8/30
48/48 [==============================] - 0s 559us/step - loss: 0.4358 - accuracy: 0.8259
Epoch 9/30
48/48 [==============================] - 0s 529us/step - loss: 0.4114 - accuracy: 0.8357
Epoch 10/30
48/48 [==============================] - 0s 571us/step - loss: 0.3881 - accuracy: 0.8440

In [16]:
model.evaluate(
  X_test,
  y_test
)

8/8 [==============================] - 0s 627us/step - loss: 0.2517 - accuracy: 0.8917


[0.2517007291316986, 0.8916666507720947]

In [17]:
import os
os.getcwd()

model.save(os.getcwd())

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: C:\Users\xico2\IronHack\Labs\lab-deep-learning\your-code\assets


In [18]:
# your code here


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [19]:
# your code here
import keras
import numpy as np
model = keras.models.load_model(os.getcwd())

# Predict on the first 5 rows.
predictions = model.predict(X_test[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1))

display(y_test[:5].astype(int))



[0 1 1 1 1]


879    0
496    1
14     1
546    1
55     1
Name: class, dtype: int32

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [85]:
import tensorflow as tf
model = Sequential([# as far as we know, all networks are sequential
  Dense(64, activation='relu', input_shape=(9,)),
    Dense(64, activation='relu'),# 784= 28*28 dense networks means all neurons in one layer are connected to all neuronsof the next layer
    Dense(64, activation='relu'),# choosing relu instead of sigmoid, this is somewhat common
  Dense(10, activation='softmax'),   # the softmax actiavation is the last one to compensate for the high volume additions
])

opt = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(
  optimizer=opt, #here we could use stochastic gradient descent, but adam is a de facto standard
  loss='sparse_categorical_crossentropy', #this is how we create the original blam to play the blame game
  metrics=['accuracy'],
)

In [86]:
# your code here
history = model.fit(
  X_train,
  y_train, # just to make sure the outputs are not considered numeric (because, ya know, they are numbers...)
  epochs=60, # go 5 times through the whole dataset
  batch_size=15, # send 10 images at a time before you tweak the network again, to make it faster
)

Epoch 1/60
48/48 [==============================] - 0s 768us/step - loss: 1.4611 - accuracy: 0.5251
Epoch 2/60
48/48 [==============================] - 0s 619us/step - loss: 0.6321 - accuracy: 0.6407
Epoch 3/60
48/48 [==============================] - 0s 589us/step - loss: 0.5845 - accuracy: 0.6950
Epoch 4/60
48/48 [==============================] - 0s 582us/step - loss: 0.5316 - accuracy: 0.7535
Epoch 5/60
48/48 [==============================] - 0s 723us/step - loss: 0.5083 - accuracy: 0.7604
Epoch 6/60
48/48 [==============================] - 0s 647us/step - loss: 0.4402 - accuracy: 0.8343
Epoch 7/60
48/48 [==============================] - 0s 570us/step - loss: 0.3927 - accuracy: 0.8454
Epoch 8/60
48/48 [==============================] - 0s 619us/step - loss: 0.3569 - accuracy: 0.8607
Epoch 9/60
48/48 [==============================] - 0s 593us/step - loss: 0.3001 - accuracy: 0.8928
Epoch 10/60
48/48 [==============================] - 0s 568us/step - loss: 0.2644 - accuracy: 0.9081

In [87]:
model.evaluate(
  X_test,
  y_test
)


8/8 [==============================] - 0s 759us/step - loss: 0.1368 - accuracy: 0.9625


[0.13681451976299286, 0.9624999761581421]

**Which approach(es) did you find helpful to improve your model performance?**

In [84]:
# your answer here
#I could see that by adding more hidden layers it increases that accuracy very quickly right in the first epochs
#As we increase the learning rate from 0.01 to 0.10 the model get's stuck on a nrealy 0.65 and do not evolves along the epochs
#I also tweaked the number of epochs to a higer value

#Still I didn't figured out what would be the most appropriate neural network features/schema to this problem! A mini class would be awsome!